@startuml

hide empty methods

class Usager #LightPink

class TransportProfessionnel #LightGray

class Evaluation #LightYellow

class Professionnel #LightGray 

class Statut #LightGray 

class Transport #LightGray {
    idTrajet : Identifiant [1..1]
    typeTransport : Code [0..1]
    typeMotorisation : Code [0..1]
    transporteur : EntiteJuridique [0..1]
    adresseDepart : Adresse [0..1]
    adresseDestination : Adresse [0..1]
    budgetPrevisionnel : Montant [0..1]
    budgetReel : Montant [0..1]
    distance : Mesure [0..1]
    dureeTheorique : Mesure [0..1]
    dateDebutTransport : DateHeure [1..1]
    dateFinTransport : DateHeure [1..1]
}

class TransportUsager #LightGray {
    accompagnement : Indicateur [0..1]
    asepsieRigoureuse : Indicateur [0..1]
    natureTransport : Code [0..1]
}

class Evenement #LightGray {
    idEvenement : Identifiant [1..1]
    typeEvenement : Code [0..*]
    libelleEvenement : Texte [0..1]
    commentaireEvenement : Texte [0..*]
    compteRenduEvenement : Texte [0..1]
    pieceJointeEvenement : ObjetBinaire [0..*]
    lieuEvenement : Lieu [0..1]
    structureEnCharge : EntiteJuridique [0..1]
    dateDebutEvenement : DateHeure [1..1]
    dateFinEvenement : DateHeure [1..1]
    evenementHorsPrestation : Indicateur [0..1]
    motifEvenement : Texte [0..1]
    usagerPresent : Indicateur [0..1]
    motifNonRealisation : Code [0..1]
    repas : Indicateur [0..1]
    typeRessourceUtilisee : Code [0..*]
    detailTypeRessourceUtilisee : Code [0..*]
    dateDerniereModification : DateHeure [0..1]
    dateValidation : DateHeure [0..1]
}

Usager "1..*" -- "0..*" Evenement
Professionnel "0..*" -- "0..*" Evenement
Transport <|-- TransportProfessionnel
Transport <|-- TransportUsager
TransportUsager "0..*" -- "1" Evenement
TransportProfessionnel "0..*" -- "1" Professionnel
Evenement "0..1" -- "0..1" Evaluation
Evenement "1" -- "0..*" Statut


@enduml