@startuml

package "Transférer des données DUI" as transfert #FloralWhite {
    package "Transférer les données DUI vers un SI tiers" as transfertSI #Moccasin {
        package "Transférer des données DUI vers d'autres SI" #Moccasin
        package "Transférer les données d'un logiciel DUI vers SIDOBA" #LightBlue
    }
    package "Portabilité de données DUI" as portabilite #Moccasin {
        package "Changer d'ESMS" #LightBlue
        package "Changer de logiciel métier" #LightBlue
    }
}

package "Suivi des décisions d'orientation" as suivi #FloralWhite {
    package "SI-ESMS" #FloralWhite
    package "SI-SdO" #FloralWhite
}

portabilite -[hidden]- transfertSI
[SI-SdO] -[hidden]- [SI-ESMS]


@enduml