@startuml

object Usager #LightPink


package "Identification et coordonnées" as id #PaleGreen {
    object Courrier #PaleGreen
    object Adresse #PaleGreen
    object Télécommunication #PaleGreen
}

Télécommunication "*" - "1    " Usager
Adresse "*" - Usager
Courrier "*" - Usager


package "Autorisations\nadministratives" as Auto #PeachPuff {
    object "Autorisation\nadministrative" as auto #PeachPuff
}

auto " *   " -- "1" Usager


package "Droits sociaux et de santé" as Droit #LightYellow {
    object "Assurance maladie\ncomplémentaire" as assC #LightYellow
    object "Assurance maladie obligatoire" as assO #LightYellow
    object Décision #LightYellow
    object "Droit\nprestation" as presta #LightYellow
    object "Détail\nprestation" as detail #LightYellow
    object "Prise charge" as pc #LightYellow
    object Quantification #LightYellow
}

hide @unlinked

Usager "1" -- " *  "  assC
Usager "1" -- "0..1" assO
Usager "1" -- " *  " Décision
Décision "1" - " 0..1" presta
presta "1" -- "0..1   " detail
pc "*" - "1" detail
Quantification "0..1" - " 1" pc

assO -[hidden]- assC

package Séjours #Thistle {
    object Séjour #Thistle
    object Solde #Thistle
    object Réservation #Thistle
    object Inventaire #Thistle
    object Contrat #Thistle
}

Usager "1" - "  *  " Séjour
Solde "*" - "1" Séjour
Inventaire "0..1   "-- "1" Séjour
ESSMS "1" -- "*" Séjour
Contrat "*" -- "1  " Séjour
Réservation "*" -- "1" Usager
Réservation "*" -- "1   " presta
Séjour "*" -- "1 " presta

Séjour -[hidden]- Réservation


package "Environnement\net ressources" as Env #LightBlue {
    object "Contact personne\nmorale" as contactM #LightBlue
    object "Contact personne\nphysique" as contactP #LightBlue
    object "Permis conduire" as permis #LightBlue
    object Transport #LightBlue
    object "Compte bancaire" as cb #LightBlue
    object Ressource #LightBlue
    object "Mesure protection" as mp #LightBlue
}

Usager "1" - "*" contactM
Usager - "*\n" contactP 
Usager - "*" permis 
Usager - "*" Transport 
Usager "1" - " *" cb
Usager - "*" Ressource
Usager - "*" mp

contactP -[hidden]- Ressource
contactM -[hidden]- cb
mp -[hidden]- Transport
mp -[hidden]- permis


id -[hidden]- Env

@enduml