@startuml

object Usager #LightPink


package "Identification et coordonnées" as id #PaleGreen {
    object Courrier #PaleGreen
    object Adresse #PaleGreen
    object Télécommunication #PaleGreen
}

Télécommunication - Usager
Adresse - Usager
Courrier - Usager


package "Autorisations administratives" as Auto #PeachPuff {
    object "Autorisation\nadministrative" as auto #PeachPuff
}

auto -- Usager


package "Droits sociaux et de santé" as Droit #LightYellow {
    object "Assurance maladie\ncomplémentaire" as assC #LightYellow
    object "Assurance maladie\nobligatoire" as assO #LightYellow
    object Décision #LightYellow
    object "Droit\nprestation" as presta #LightYellow
    object "Détail\nprestation" as detail #LightYellow
    object "Prise charge" as pc #LightYellow
    object Quantification #LightYellow
}

Usager -- assC
Usager -- assO
Usager -- Décision
Décision - presta
presta -- detail
pc - detail
Quantification - pc

assO -[hidden]- assC


package Séjours #Thistle {
    object Séjour #Thistle
    object Solde #Thistle
    object Réservation #Thistle
    object Inventaire #Thistle
    object ESSMS #Thistle
    object Contrat #Thistle
}

Usager - Séjour
Solde - Séjour
Inventaire -- Séjour
ESSMS -- Séjour
Contrat -- Séjour
Réservation -- Usager
Réservation -- presta
Séjour -- presta

Séjour -[hidden]- Réservation


package "Environnement et ressources" as Env #LightBlue {
    object "Contact personne\nmorale" as contactM #LightBlue
    object "Contact personne\nphysique" as contactP #LightBlue
    object "Permis conduire" as permis #LightBlue
    object Transport #LightBlue
    object "Compte bancaire" as cb #LightBlue
    object Ressource #LightBlue
    object "Mesure protection" as mp #LightBlue
}

Usager - contactM
Usager - contactP 
Usager - permis 
Usager - Transport 
Usager - cb
Usager - Ressource
Usager - mp

cb -[hidden]- contactP
Ressource -[hidden]- contactM
mp -[hidden]- Transport


id -[hidden]- Env

@enduml