@startuml

"Logiciel DUI" -> "Logiciel DUI ou SIDOBA" : Flux 2.1 **MiseAJourDocument** \n HTTP PUT [base]/DocumentReference/[id]
"Logiciel DUI" <-- "Logiciel DUI ou SIDOBA" : Flux 2.2 **ResultatMiseAJourDocument** \n HTTP 200 OK (+ ressource "DocumentReference")

@enduml
