@startuml

"Logiciel DUI" -> "Logiciel DUI ou SI tiers" : Flux 1.1 **AjoutDocument** \n HTTP POST [base] (+ ressource "DocumentReference")
"Logiciel DUI" <-- "Logiciel DUI ou SI tiers" : Flux 1.2 **ResultatAjoutDocument** \n HTTP 201 Created (+ ressource "DocumentReference")

@enduml
