@startuml


map "AssuranceMaladieObligatoire : [[contenu_dossier_corps_cda.html Entrée FR-Organisme-assurance-maladie]]" as AssuranceMaladieObligatoire #LightYellow {
    ouvrantDroit => participant[@typeCode=HLD]/participantRole/id
}

map "AssuranceMaladieComplementaire : [[contenu_dossier_corps_cda.html Entrée FR-Organisme-assurance-maladie]]" as AssuranceMaladieComplementaire #LightYellow {
    ouvrantDroit => participant[@typeCode=HLD]/participantRole/id
}

@enduml