@startuml


map "Evenement : [[contenu_dossier_corps_cda.html#entrée-fr-evenement Entrée FR-Evenement]]" as Evenement #back:ghostWhite;header:LightGray {
    idEvenement => id
    typeEvenement => code/qualifier \n code/originalText
    libelleEvenement => text
    commentaireEvenement => [[contenu_dossier_corps_cda.html#entrée-fr-commentaire-er Entrée FR-CommentaireER]]
    compteRenduEvenement => [[contenu_dossier_corps_cda.html#entrée-fr-reference-interne Entrée FR-Reference-interne]]
    pieceJointeEvenement => [[contenu_dossier_corps_cda.html#entrée-fr-reference-interne Entrée FR-Reference-interne]]
    dateDebutEvenement => effectiveTime/low
    dateFinEvenement => effectiveTime/high
    evenementHorsPrestation => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    motifEvenement => text
    usagerPresent => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    repas => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    typeRessourceUtilisee => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    detailTypeRessourceUtilisee => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value/qualifier
    dateModificationEvenement => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
}
map "Transport : [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-professionnel Entrée FR-Transport-du-professionnel]] / [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-patient Entrée FR-Transport-du-patient]]" as Transport#back:ghostWhite;header:LightGray {
    idTrajet => id
    typeTransport => code
    typeMotorisation => code/qualifier
    adresseDepart => participant[@typeCode=ORG]/participantRole/addr
    adresseDestination => participant[@typeCode=DST]/participantRole/addr
    budgetPrevisionnel => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    budgetReel => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    distance => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    dureeTheorique => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    dateDebutTransport => effectiveTime/low
    dateFinTransport => effectiveTime/high

}
map "Professionnel : [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-professionnel Entrée FR-Transport-du-professionnel]]" as ProfessionnelTransport #back:Ivory;header:LightYellow  {
    idNat_PS => participant[@typeCode=RCV]/participantRole/id
    civilite => participant[@typeCode=RCV]/participantRole/playingEntity/name/prefix
    nom => participant[@typeCode=RCV]/participantRole/playingEntity/name/family
    prenom => participant[@typeCode=RCV]/participantRole/playingEntity/name/given
    profession => participant[@typeCode=RESP]/participantRole/playingEntity/code
    role => NA
}

map "EtablissementDeRattachement : [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-professionnel Entrée FR-Transport-du-professionnel]]" as etablissementDeRattachement #back:Ivory;header:LightYellow {
    idNat_Struct => participant[@typeCode=RCV]/participantRole/scopingEntity/id
    raisonSocial => participant[@typeCode=RCV]/participantRole/scopingEntity/desc
}

map "Transporteur [[contenu_dossier_corps_cda.html#entrée-fr-evenement Entrée FR-Evenement]]" as transporteur #back:Ivory;header:LightYellow  {
    idNat_Struct => performer/assignedEntity/representedOrganization/id
    raisonSocial => performer/assignedEntity/representedOrganization/name
}

map "StructureEnCharge [[contenu_dossier_corps_cda.html#entrée-fr-evenement Entrée FR-Evenement]]" as structureEnCharge #back:Ivory;header:LightYellow  {
    idNat_Struct => participant[@typeCode=RESP]/participantRole/scopingEntity/id
    raisonSocial => participant[@typeCode=RESP]/participantRole/scopingEntity/desc
}


map "TransportProfessionnel: [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-professionnel Entrée FR-Transport-du-professionnel]]" as TransportPro#back:ghostWhite;header:LightGray {
}



map "TransportUsager : [[contenu_dossier_corps_cda.html#entrée-fr-transport-du-patient Entrée FR-Transport-du-patient]]" as TransportUsager#back:ghostWhite;header:LightGray {
    accompagnement => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    asepsieRigoureuse => [[contenu_dossier_corps_cda.html#entrée-fr-simple-observation Entrée FR-Simple-Observation]] value
    natureTransport => code/qualifier

}

map "LieuEvenement : [[contenu_dossier_corps_cda.html#entrée-fr-evenement Entrée FR-Evenement]]" as Lieu #back:Ivory;header:LightYellow  {
    identifiant => participant[@typeCode=LOC]/participantRole/scopingEntity/id    
    nom => participant[@typeCode=LOC]/participantRole/scopingEntity/desc
    adresse => participant[@typeCode=LOC]/participantRole/addr
    telecommunication => participant[@typeCode=LOC]/participantRole/telecom 
}

map "Evaluation : [[contenu_dossier_corps_cda.html#entrée-fr-reference-interne Entrée FR-Rerence-interne]] référençant une entrée FR-Evaluation" as Evaluation #back:Ivory;header:LightYellow {
}

map "Statut : [[contenu_dossier_corps_cda.html#entrée-fr-statut Entrée FR-Statut]]" as Statut #back:Ivory;header:LightYellow{
    statut => value
    motifNonRealisation => value/qualifier
    dateModificationStatut => effectiveTime
}

map "Professionnel : [[contenu_dossier_corps_cda.html#entrée-fr-evenement Entrée FR-Evenement]]" as ProfessionnelEvn #back:Ivory;header:LightYellow{
    idNat_PS => performer/assignedEntity/id
}

map "Auteur : [[contenu_dossier_corps_cda.html#entrée-fr-statut Entrée FR-Statut]]" as AuteurStatut #back:Ivory;header:LightYellow {
    idNat_PS => author/assignedAuthor/id
    civilite => author/assignedAuthor/assignedPerson/name/prefix
    nom => author/assignedAuthor/assignedPerson/name/family
    prenom => author/assignedAuthor/assignedPerson/name/given
    profession => author/assignedAuthor/code
    role => author/functionCode
}

map "EtablissementDeRattachement : [[contenu_dossier_corps_cda.html#entrée-fr-statut Entrée FR-Statut]]" as etablissementDeRattachementAuthStatut #back:Ivory;header:LightYellow {
    idNat_Struct => author/assignedAuthor/representedOrganization/id
    raisonSocial => author/assignedAuthor/representedOrganization/name
}




Evenement "1" -- "0..*" Statut
Evenement "0..*" -right- "0..1" Lieu  
ProfessionnelEvn "0..*" -- "0..*" Evenement
structureEnCharge "0..1" -right- "0..*" Evenement
Evenement "1" -up- "0..*" TransportPro 
TransportPro "0..*" -right- "1" ProfessionnelTransport
etablissementDeRattachement "0..1" -- "0..*" ProfessionnelTransport
Transport <|-- TransportPro
Transport <|-- TransportUsager
TransportUsager "0..*" -- "1" Evenement
Evenement "0..1" -- "0..1" Evaluation
transporteur "0..1" -- "0..*" Transport
Statut "0..*" -- "0..1" AuteurStatut
AuteurStatut "0..*" -- "0..1" etablissementDeRattachementAuthStatut




@enduml