@startuml

map "EntiteJuridique : En-tête du document CDA" as EJ #back:Ivory;header:LightYellow {
    idNat_Struct => participant/associatedEntity/id
    raisonSocial => participant/associatedEntity/scopingOrganization/name
    statutJuridique => X
}

@enduml