@startuml


map "Sejour : [[contenu_dossier_corps_cda.html Entrée FR-Sejour]]" as Sejour #back:LavenderBlush;header:Thistle{
    dateAdmission => effectiveTime.low
    dateEntree => [[contenu_dossier_corps_cda.html Entrée FR-Modalite-entree]] effectiveTime
    libelleModeEntree => [[contenu_dossier_corps_cda.html Entrée FR-Modalite-entree]] text
    dateSortiePrevisionnelle => [[contenu_dossier_corps_cda.html Entrée FR-Modalite-sortie avec @moodCode=INT]]  effectiveTime
    dateSortie => [[contenu_dossier_corps_cda.html Entrée FR-Modalite-sortie avec @moodCode=EVN]]  effectiveTime
    libelleModeSortie => [[contenu_dossier_corps_cda.html Entrée FR-Modalite-sortie]]  text
    numeroDossier => id
    commentaire => [[contenu_dossier_corps_cda.html Entrée FR-CommentaireER]]
}


map "ESMSS: [[contenu_dossier_corps_cda.html Entrée FR-Sejour]]" as ESSMS #back:LavenderBlush;header:Thistle{
    idNat_PS => participant[@typeCode=LOC].participantRole.id
}

map "Evenement : [[contenu_dossier_corps_cda.html Entrée FR-Rerence-interne]] référençant une entrée FR-Evenement" as Evenement #back:LightYellow;header:LightYellow{
}

Sejour "0..*" -- "0..1" ESSMS
Sejour "0..1"--"0..*" Evenement


@enduml