@startuml


map "Usager : [[contenu_dossier_entete_cda.html#recordtarget En-tête recordTarget]]" as Usager #back:IMPLEMENTATION;header:LightPink {
    matriculeINS => patientRole/id
    numSecuriteSociale => patientRole/id
    identifiantLocalUsagerESSMS => patientRole/id
    numeroIndividuInitial => patientRole/id
    nomNaissance => patientRole/patient/name/family[@qualifier=BR]
    nomUsage => patientRole/patient/name/family[@qualifier=CL]
    prenom => patientRole/patient/name/given @qualifier non utilisé
    premierPrenomActeNaissance  => patientRole/patient/name/given[@qualifier=BR]
    prenomUtilise => patientRole/patient/name/given[@qualifier=CL]
    sexe => patientRole/patient/administrativeGenderCode
    civilite => patientRole/patient/name/prefix
    dateNaissance => patientRole/patient/birthTime
    ordreNaissance => patientRole/patient/sdtc:multipleBirthOrderNumber
    communeNaissance => patientRole/patient/brithPlace/place/addr/county
    paysNaissance => patientRole/patient/brithPlace/place/addr/county
}

@enduml