@startuml


map "Usager : [[contenu_dossier_entete_cda.html En-tête recordTarget]]" as Usager #back:IMPLEMENTATION;header:LightPink {
    numeroIndividu => id
    INS=> id
    nomNaissance => name/family[@qualifier=BR]
    nomUsage => name/family[@qualifier=CL]
    prenom => name/given
    sexe=> administrativeGenderCode
    dateNaissance => birthTime
    ordreNaissance => multipleBirthOrderNumber
    communeNaissance => brithPlace/place/addr/county
    paysNaissance => brithPlace/place/addr/country
}

@enduml