@startuml


map "Evenement : [[contenu_dossier_corps_cda.html Entrée FR-Evenement]]" as Evenement #back:ghostWhite;header:LightGray {
    idEvenement => id
    typeEvenement => code
    libelleEvenement => text
    commentaireEvenement => [[contenu_dossier_corps_cda.html Entrée FR-CommentaireER]]
    compteRenduEvenement => [[contenu_dossier_corps_cda.html Entrée FR-Reference-interne]]
    pieceJointeEvenement => [[contenu_dossier_corps_cda.html Entrée FR-Reference-interne]]
    statutEvenement => [[contenu_dossier_corps_cda.html Entrée FR-Statut]] code
    dateDebutEvenement => effectiveTime/low
    dateFinEvenement => effectiveTime/high
    evenementHorsPrestation => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    motifEvenement => text
    usagerPresent => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    motifNonRealisation => [[contenu_dossier_corps_cda.html Entrée FR-Statut]] value/qualifier 
    repas => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    typeRessourceUtilisee => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    detailTypeRessourceUtilisee => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value/qualifier
    dateDerniereModification => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    dateValidation => [[contenu_dossier_corps_cda.html Entrée FR-Statut]] effectiveTime
}
map "Transport : [[contenu_dossier_corps_cda.html Entrée FR-Transport-du-professionnel/FR-Transport-du-patient]]" as Transport#back:ghostWhite;header:LightGray {
    idTrajet => id
    typeTransport => code
    typeMotorisation => code/qualifier
    adresseDepart => participant[@typeCode=ORG]/participantRole/addr
    adresseDestination => participant[@typeCode=DST]/participantRole/addr
    budgetPrevisionnel => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    budgetReel => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    distance => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    dureeTheorique => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    dateDebutTransport => effectiveTime/low
    dateFinTransport => effectiveTime/high

}
map "Professionnel : [[contenu_dossier_corps_cda.html Entrée FR-Transport-du-professionnel]]" as Professionnel #back:Ivory;header:LightYellow  {
    idNat_PS => participant[@typeCode=RCV]/participantRole/id 
}

map "Transporteur [[contenu_dossier_corps_cda.html Entrée FR-Evenement]]" as transporteur #back:Ivory;header:LightYellow  {
    idNat_Struct => performer/assignedEntity/representedOrganization/id
}

map "StructureEnCharge [[contenu_dossier_corps_cda.html Entrée FR-Evenement]]" as structureEnCharge #back:Ivory;header:LightYellow  {
    idNat_Struct => participant[@typeCode=RESP]/participantRole/id
}


map "TransportProfessionnel: [[contenu_dossier_corps_cda.html Entrée FR-Transport-du-professionnel]]" as TransportPro#back:ghostWhite;header:LightGray {
}



map "TransportUsager : [[contenu_dossier_corps_cda.html Entrée FR-Transport-du-patient]]" as TransportUsager#back:ghostWhite;header:LightGray {
    natureTransport => code/qualifier
    accompagnement => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
    asepsieRigoureuse => [[contenu_dossier_corps_cda.html Entrée FR-Simple-Observation]] value
}

map "LieuEvenement : [[contenu_dossier_corps_cda.html Entrée FR-Evenement]]" as Lieu #back:Ivory;header:LightYellow  {
    identifiant => participant[@typeCode=LOC]/participantRole/id    
 
}

map "Evaluation : [[contenu_dossier_corps_cda.html Entrée FR-Rerence-interne]] référençant une entrée FR-Evaluation" as Evaluation #back:Ivory;header:LightYellow {
}

map "Statut : [[contenu_dossier_corps_cda.html Entrée FR-Statut]]" as statut #back:Ivory;header:LightYellow {
}


Evenement "0..*" -- "0..1" Lieu  
Professionnel "0..*" -- "0..*" Evenement
structureEnCharge "0..1" -- "0..*" Evenement
Transport <|-- TransportPro
Transport <|-- TransportUsager
TransportUsager "0..*" -- "1" Evenement
TransportPro "0..*" -- "1" Professionnel
Evenement "0..1" -- "0..1" Evaluation
Evenement "1" -- "0..*" statut
transporteur "0..1" -- "0..*" Transport


@enduml