@startuml

map "Professionnel : En-tête du document CDA" as Professionnel #back:Ivory;header:LightYellow{
    idNat_PS => participant/associatedEntity/id
    civilite => participant/associatedEntity/associatedPerson/prefix
    nom => participant/associatedEntity/associatedPerson/family
    prenom => participant/associatedEntity/associatedPerson/given
    specialite => participant/associatedEntity/code
    etablissementDeRattachement => participant/associatedEntity/scopingOrganization/id
}


@enduml