@startuml

map "Statut : [[contenu_dossier_corps_cda.html Entrée FR-Statut]]" as Statut #back:Ivory;header:LightYellow{
    statut => code
    dateModificationStatut => effectiveTime
    auteur => author
   
}


@enduml