@startuml


map "Sejour : [[contenu_dossier_corps_cda.html#entrée-fr-sejour Entrée FR-Sejour]]" as Sejour #back:LavenderBlush;header:Thistle{
    dateAdmission => [[contenu_dossier_corps_cda.html#entrée-fr-sejour-admission Entrée FR-Sejour-Admission]] effectiveTime
    dateEntreePrevisionnelle => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-entree Entrée FR-Modalite-entree avec @moodCode=INT]] effectiveTime
    dateEntree => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-entree Entrée FR-Modalite-entree avec @moodCode=EVN]] effectiveTime
    libelleModeEntree => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-entree Entrée FR-Modalite-entree]] text
    dateSortiePrevisionnelle => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-sortie Entrée FR-Modalite-sortie avec @moodCode=INT]]  effectiveTime
    dateSortie => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-sortie Entrée FR-Modalite-sortie avec @moodCode=EVN]]  effectiveTime
    libelleModeSortie => [[contenu_dossier_corps_cda.html#entrée-fr-modalite-sortie Entrée FR-Modalite-sortie]]  text
    idSejour => [[contenu_dossier_corps_cda.html#entrée-fr-sejour-admission Entrée FR-Sejour-Admission]] id
    commentaire => [[contenu_dossier_corps_cda.html#entrée-fr-commentaire-er Entrée FR-CommentaireER]]
}


map "ESSMS: [[contenu_dossier_corps_cda.html#entrée-fr-sejour-admission Entrée FR-Sejour-Admission]]" as ESSMS #back:Ivory;header:LightYellow {
    idNat_Struct => participant[@typeCode=RESP]/participantRole/scopingEntity/id
    raisonSocial => participant[@typeCode=RESP]/participantRole/scopingEntity/desc
}

map "Evenement : [[contenu_dossier_corps_cda.html#entrée-fr-reference-interne Entrée FR-Rerence-interne]] référençant une entrée FR-Evenement" as Evenement #back:LightYellow;header:LightYellow{
}

Sejour "0..*" -- "1..1" ESSMS
Sejour "0..1"--"0..*" Evenement


@enduml