@startuml

:"Rôle"\nProducteur: as P #Moccasin
:"Rôle"\nConsommateur: as C #Moccasin
:"Système"\nLogiciel DUI: as L1 #Moccasin
:"Système"\nLogiciel DUI: as L2 #Moccasin

(Changer d'ESMS) as c #Moccasin

c - C
P - c
P -- L1
C -- L2

@enduml