@startuml

:"Rôle"\nProducteur: as P #Moccasin
:"Rôle"\nConsommateur: as C #Moccasin
:"Système"\nLogiciel DUI: as L #Moccasin
:"Système"\nLogiciel DUI: as S #Moccasin
:"Système"\nSI Tiers: as O #Moccasin

(Export des données d'un logiciel DUI) as c #Moccasin

c - C
P - c
P -- L
C -- S
C -- O

@enduml