@startuml

:"Rôle"\nProducteur: as P #Moccasin
:"Rôle"\nConsommateur: as C #Moccasin
:"Système"\nLogiciel DUI: as L #Moccasin
:"Système"\nLogiciel SIDOBA: as S #Moccasin

(Transférer des données d'un logiciel\nDUI vers SIDOBA) as c #Moccasin

c - C
P - c
P -- L
C -- S

@enduml