@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class TDDUIBundle{

             Bundle.type => [None..None]
             Bundle.entry => [1..None]
             Bundle.entry:DUIDocumentReference => [1..*]
             Bundle.entry:DUIDocumentReference.resource => [1..None]
             Bundle.entry:DUIDocumentReference.request => [1..None]
             Bundle.entry:DUIDocumentReference.request.method => [None..None]
        } 

        class TDDUIDocumentReference{

             DocumentReference.meta.versionId => [None..None]
             DocumentReference.modifierExtension => [None..0]
             DocumentReference.masterIdentifier => [1..None]
             DocumentReference.identifier => [None..0]
             DocumentReference.status => [None..None]
             DocumentReference.docStatus => [None..0]
             DocumentReference.type => [None..None]
             DocumentReference.category => [None..1]
             DocumentReference.subject => [None..None]
             DocumentReference.date => [None..None]
             DocumentReference.author => [None..None]
             DocumentReference.authenticator => [None..None]
             DocumentReference.relatesTo => [None..None]
             DocumentReference.description => [None..None]
             DocumentReference.securityLabel => [None..None]
             DocumentReference.content => [None..1]
             DocumentReference.content.attachment.contentType => [1..None]
             DocumentReference.content.attachment.language => [None..None]
             DocumentReference.content.attachment.data => [1..None]
             DocumentReference.content.attachment.url => [None..0]
             DocumentReference.content.attachment.size => [None..None]
             DocumentReference.content.attachment.hash => [None..None]
             DocumentReference.content.attachment.title => [1..None]
             DocumentReference.content.attachment.creation => [None..None]
             DocumentReference.content.format => [None..None]
             DocumentReference.context => [None..None]
             DocumentReference.context.event => [None..1]
             DocumentReference.context.period => [None..None]
             DocumentReference.context.facilityType => [None..None]
             DocumentReference.context.practiceSetting => [None..None]
             DocumentReference.context.sourcePatientInfo => [None..None]
         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> TDDUIBundle

 class "DocumentReference" as  classabc067272ee1964cc2c74c1c1a1854f5 

    classabc067272ee1964cc2c74c1c1a1854f5 --> TDDUIDocumentReference
}
@enduml